version: '3.9'

services:
  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py loaddata initial_data.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "${FRONT_END_PORT}:${FRONT_END_PORT}"
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app/frontend

  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
    mynetwork:
      driver: bridge
