# Generated by Django 5.0.7 on 2024-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contacts_address_alter_contacts_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-published_date'],
            },
        ),
    ]
